services:
    postgres:
        image: postgres:16-alpine
        container_name: expense-tracker-db
        restart: unless-stopped
        environment:
            POSTGRES_USER: expense-tracker
            POSTGRES_PASSWORD: expense-tracker123
            POSTGRES_DB: expense-tracker
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
